// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/bodyStrong.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Bdl.Proto {

  /// <summary>Holder for reflection information generated from proto/bodyStrong.proto</summary>
  public static partial class BodyStrongReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/bodyStrong.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BodyStrongReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZwcm90by9ib2R5U3Ryb25nLnByb3RvEg1jb20uYmRsLnByb3RvIpICChFC",
            "b2R5U3Ryb25nTWVzc2FnZRJBCgttZXNzYWdlVHlwZRgBIAEoDjIsLmNvbS5i",
            "ZGwucHJvdG8uQm9keVN0cm9uZ01lc3NhZ2UuTWVzc2FnZVR5cGUSOwoQaGVh",
            "cnRiZWF0UmVxdWVzdBgCIAEoCzIfLmNvbS5iZGwucHJvdG8uSGVhcnRiZWF0",
            "UmVxdWVzdEgAEj0KEWhlYXJ0YmVhdFJlc3BvbnNlGAMgASgLMiAuY29tLmJk",
            "bC5wcm90by5IZWFydGJlYXRSZXNwb25zZUgAIjIKC01lc3NhZ2VUeXBlEhAK",
            "DEhFQUVSQkVBVFJFURAAEhEKDUhFQUVSQkVBVFJFU1AQAUIKCghkYXRhQm9k",
            "eSJzChBIZWFydGJlYXRSZXF1ZXN0EhAKCHVuaXF1ZUlkGAEgASgJEhMKC3Nl",
            "dHRpbmdKU09OGAIgASgJEhMKC3Byb2R1Y3ROYW1lGAMgASgJEg4KBnN0YXR1",
            "cxgEIAEoCRITCgt1c2VEZWFkVGltZRgFIAEoCSKtAQoRSGVhcnRiZWF0UmVz",
            "cG9uc2USQwoMcmVzcG9uc2VUeXBlGAEgASgOMi0uY29tLmJkbC5wcm90by5I",
            "ZWFydGJlYXRSZXNwb25zZS5SZXNwb25zZVR5cGUSEgoKYXR0YWNobWVudBgC",
            "IAEoCSI/CgxSZXNwb25zZVR5cGUSCQoFTk9NQUwQABIOCgpBRERVU0VUSU1F",
            "EAESCAoETE9DSxACEgoKBlVOTE9DSxADQiAKDWNvbS5iZGwucHJvdG9CDUNv",
            "bW1vbk1lc3NhZ2VIAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Bdl.Proto.BodyStrongMessage), global::Com.Bdl.Proto.BodyStrongMessage.Parser, new[]{ "MessageType", "HeartbeatRequest", "HeartbeatResponse" }, new[]{ "DataBody" }, new[]{ typeof(global::Com.Bdl.Proto.BodyStrongMessage.Types.MessageType) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Bdl.Proto.HeartbeatRequest), global::Com.Bdl.Proto.HeartbeatRequest.Parser, new[]{ "UniqueId", "SettingJSON", "ProductName", "Status", "UseDeadTime" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Bdl.Proto.HeartbeatResponse), global::Com.Bdl.Proto.HeartbeatResponse.Parser, new[]{ "ResponseType", "Attachment" }, null, new[]{ typeof(global::Com.Bdl.Proto.HeartbeatResponse.Types.ResponseType) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// protoc --java_out=src/main/java  proto/bodyStrong.proto
  /// </summary>
  public sealed partial class BodyStrongMessage : pb::IMessage<BodyStrongMessage> {
    private static readonly pb::MessageParser<BodyStrongMessage> _parser = new pb::MessageParser<BodyStrongMessage>(() => new BodyStrongMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BodyStrongMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Bdl.Proto.BodyStrongReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BodyStrongMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BodyStrongMessage(BodyStrongMessage other) : this() {
      messageType_ = other.messageType_;
      switch (other.DataBodyCase) {
        case DataBodyOneofCase.HeartbeatRequest:
          HeartbeatRequest = other.HeartbeatRequest.Clone();
          break;
        case DataBodyOneofCase.HeartbeatResponse:
          HeartbeatResponse = other.HeartbeatResponse.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BodyStrongMessage Clone() {
      return new BodyStrongMessage(this);
    }

    /// <summary>Field number for the "messageType" field.</summary>
    public const int MessageTypeFieldNumber = 1;
    private global::Com.Bdl.Proto.BodyStrongMessage.Types.MessageType messageType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Bdl.Proto.BodyStrongMessage.Types.MessageType MessageType {
      get { return messageType_; }
      set {
        messageType_ = value;
      }
    }

    /// <summary>Field number for the "heartbeatRequest" field.</summary>
    public const int HeartbeatRequestFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Bdl.Proto.HeartbeatRequest HeartbeatRequest {
      get { return dataBodyCase_ == DataBodyOneofCase.HeartbeatRequest ? (global::Com.Bdl.Proto.HeartbeatRequest) dataBody_ : null; }
      set {
        dataBody_ = value;
        dataBodyCase_ = value == null ? DataBodyOneofCase.None : DataBodyOneofCase.HeartbeatRequest;
      }
    }

    /// <summary>Field number for the "heartbeatResponse" field.</summary>
    public const int HeartbeatResponseFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Bdl.Proto.HeartbeatResponse HeartbeatResponse {
      get { return dataBodyCase_ == DataBodyOneofCase.HeartbeatResponse ? (global::Com.Bdl.Proto.HeartbeatResponse) dataBody_ : null; }
      set {
        dataBody_ = value;
        dataBodyCase_ = value == null ? DataBodyOneofCase.None : DataBodyOneofCase.HeartbeatResponse;
      }
    }

    private object dataBody_;
    /// <summary>Enum of possible cases for the "dataBody" oneof.</summary>
    public enum DataBodyOneofCase {
      None = 0,
      HeartbeatRequest = 2,
      HeartbeatResponse = 3,
    }
    private DataBodyOneofCase dataBodyCase_ = DataBodyOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataBodyOneofCase DataBodyCase {
      get { return dataBodyCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearDataBody() {
      dataBodyCase_ = DataBodyOneofCase.None;
      dataBody_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BodyStrongMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BodyStrongMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MessageType != other.MessageType) return false;
      if (!object.Equals(HeartbeatRequest, other.HeartbeatRequest)) return false;
      if (!object.Equals(HeartbeatResponse, other.HeartbeatResponse)) return false;
      if (DataBodyCase != other.DataBodyCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MessageType != 0) hash ^= MessageType.GetHashCode();
      if (dataBodyCase_ == DataBodyOneofCase.HeartbeatRequest) hash ^= HeartbeatRequest.GetHashCode();
      if (dataBodyCase_ == DataBodyOneofCase.HeartbeatResponse) hash ^= HeartbeatResponse.GetHashCode();
      hash ^= (int) dataBodyCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MessageType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MessageType);
      }
      if (dataBodyCase_ == DataBodyOneofCase.HeartbeatRequest) {
        output.WriteRawTag(18);
        output.WriteMessage(HeartbeatRequest);
      }
      if (dataBodyCase_ == DataBodyOneofCase.HeartbeatResponse) {
        output.WriteRawTag(26);
        output.WriteMessage(HeartbeatResponse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MessageType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MessageType);
      }
      if (dataBodyCase_ == DataBodyOneofCase.HeartbeatRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HeartbeatRequest);
      }
      if (dataBodyCase_ == DataBodyOneofCase.HeartbeatResponse) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HeartbeatResponse);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BodyStrongMessage other) {
      if (other == null) {
        return;
      }
      if (other.MessageType != 0) {
        MessageType = other.MessageType;
      }
      switch (other.DataBodyCase) {
        case DataBodyOneofCase.HeartbeatRequest:
          if (HeartbeatRequest == null) {
            HeartbeatRequest = new global::Com.Bdl.Proto.HeartbeatRequest();
          }
          HeartbeatRequest.MergeFrom(other.HeartbeatRequest);
          break;
        case DataBodyOneofCase.HeartbeatResponse:
          if (HeartbeatResponse == null) {
            HeartbeatResponse = new global::Com.Bdl.Proto.HeartbeatResponse();
          }
          HeartbeatResponse.MergeFrom(other.HeartbeatResponse);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MessageType = (global::Com.Bdl.Proto.BodyStrongMessage.Types.MessageType) input.ReadEnum();
            break;
          }
          case 18: {
            global::Com.Bdl.Proto.HeartbeatRequest subBuilder = new global::Com.Bdl.Proto.HeartbeatRequest();
            if (dataBodyCase_ == DataBodyOneofCase.HeartbeatRequest) {
              subBuilder.MergeFrom(HeartbeatRequest);
            }
            input.ReadMessage(subBuilder);
            HeartbeatRequest = subBuilder;
            break;
          }
          case 26: {
            global::Com.Bdl.Proto.HeartbeatResponse subBuilder = new global::Com.Bdl.Proto.HeartbeatResponse();
            if (dataBodyCase_ == DataBodyOneofCase.HeartbeatResponse) {
              subBuilder.MergeFrom(HeartbeatResponse);
            }
            input.ReadMessage(subBuilder);
            HeartbeatResponse = subBuilder;
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the BodyStrongMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum MessageType {
        /// <summary>
        ///心跳请求
        /// </summary>
        [pbr::OriginalName("HEAERBEATREQ")] Heaerbeatreq = 0,
        /// <summary>
        ///心跳回复
        /// </summary>
        [pbr::OriginalName("HEAERBEATRESP")] Heaerbeatresp = 1,
      }

    }
    #endregion

  }

  /// <summary>
  ///心跳请求
  /// </summary>
  public sealed partial class HeartbeatRequest : pb::IMessage<HeartbeatRequest> {
    private static readonly pb::MessageParser<HeartbeatRequest> _parser = new pb::MessageParser<HeartbeatRequest>(() => new HeartbeatRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HeartbeatRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Bdl.Proto.BodyStrongReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeartbeatRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeartbeatRequest(HeartbeatRequest other) : this() {
      uniqueId_ = other.uniqueId_;
      settingJSON_ = other.settingJSON_;
      productName_ = other.productName_;
      status_ = other.status_;
      useDeadTime_ = other.useDeadTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeartbeatRequest Clone() {
      return new HeartbeatRequest(this);
    }

    /// <summary>Field number for the "uniqueId" field.</summary>
    public const int UniqueIdFieldNumber = 1;
    private string uniqueId_ = "";
    /// <summary>
    ///机器码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UniqueId {
      get { return uniqueId_; }
      set {
        uniqueId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "settingJSON" field.</summary>
    public const int SettingJSONFieldNumber = 2;
    private string settingJSON_ = "";
    /// <summary>
    ///setting表的json串,对方可能更改，传上来再说
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SettingJSON {
      get { return settingJSON_; }
      set {
        settingJSON_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "productName" field.</summary>
    public const int ProductNameFieldNumber = 3;
    private string productName_ = "";
    /// <summary>
    ///产品名字 医疗康复/智能健身
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ProductName {
      get { return productName_; }
      set {
        productName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 4;
    private string status_ = "";
    /// <summary>
    ///状态 正常0和锁定1
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Status {
      get { return status_; }
      set {
        status_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "useDeadTime" field.</summary>
    public const int UseDeadTimeFieldNumber = 5;
    private string useDeadTime_ = "";
    /// <summary>
    ///使用期限 某日期 或者 9999-12-31
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UseDeadTime {
      get { return useDeadTime_; }
      set {
        useDeadTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HeartbeatRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HeartbeatRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UniqueId != other.UniqueId) return false;
      if (SettingJSON != other.SettingJSON) return false;
      if (ProductName != other.ProductName) return false;
      if (Status != other.Status) return false;
      if (UseDeadTime != other.UseDeadTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UniqueId.Length != 0) hash ^= UniqueId.GetHashCode();
      if (SettingJSON.Length != 0) hash ^= SettingJSON.GetHashCode();
      if (ProductName.Length != 0) hash ^= ProductName.GetHashCode();
      if (Status.Length != 0) hash ^= Status.GetHashCode();
      if (UseDeadTime.Length != 0) hash ^= UseDeadTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UniqueId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UniqueId);
      }
      if (SettingJSON.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SettingJSON);
      }
      if (ProductName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ProductName);
      }
      if (Status.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Status);
      }
      if (UseDeadTime.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(UseDeadTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UniqueId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UniqueId);
      }
      if (SettingJSON.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SettingJSON);
      }
      if (ProductName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProductName);
      }
      if (Status.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Status);
      }
      if (UseDeadTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UseDeadTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HeartbeatRequest other) {
      if (other == null) {
        return;
      }
      if (other.UniqueId.Length != 0) {
        UniqueId = other.UniqueId;
      }
      if (other.SettingJSON.Length != 0) {
        SettingJSON = other.SettingJSON;
      }
      if (other.ProductName.Length != 0) {
        ProductName = other.ProductName;
      }
      if (other.Status.Length != 0) {
        Status = other.Status;
      }
      if (other.UseDeadTime.Length != 0) {
        UseDeadTime = other.UseDeadTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UniqueId = input.ReadString();
            break;
          }
          case 18: {
            SettingJSON = input.ReadString();
            break;
          }
          case 26: {
            ProductName = input.ReadString();
            break;
          }
          case 34: {
            Status = input.ReadString();
            break;
          }
          case 42: {
            UseDeadTime = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///心跳回复
  /// </summary>
  public sealed partial class HeartbeatResponse : pb::IMessage<HeartbeatResponse> {
    private static readonly pb::MessageParser<HeartbeatResponse> _parser = new pb::MessageParser<HeartbeatResponse>(() => new HeartbeatResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HeartbeatResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Bdl.Proto.BodyStrongReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeartbeatResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeartbeatResponse(HeartbeatResponse other) : this() {
      responseType_ = other.responseType_;
      attachment_ = other.attachment_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeartbeatResponse Clone() {
      return new HeartbeatResponse(this);
    }

    /// <summary>Field number for the "responseType" field.</summary>
    public const int ResponseTypeFieldNumber = 1;
    private global::Com.Bdl.Proto.HeartbeatResponse.Types.ResponseType responseType_ = 0;
    /// <summary>
    ///心跳反馈类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Bdl.Proto.HeartbeatResponse.Types.ResponseType ResponseType {
      get { return responseType_; }
      set {
        responseType_ = value;
      }
    }

    /// <summary>Field number for the "attachment" field.</summary>
    public const int AttachmentFieldNumber = 2;
    private string attachment_ = "";
    /// <summary>
    ///反馈类型对附件，主要针对延期请求，可选为永久离线。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Attachment {
      get { return attachment_; }
      set {
        attachment_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HeartbeatResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HeartbeatResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResponseType != other.ResponseType) return false;
      if (Attachment != other.Attachment) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ResponseType != 0) hash ^= ResponseType.GetHashCode();
      if (Attachment.Length != 0) hash ^= Attachment.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ResponseType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ResponseType);
      }
      if (Attachment.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Attachment);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ResponseType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseType);
      }
      if (Attachment.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Attachment);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HeartbeatResponse other) {
      if (other == null) {
        return;
      }
      if (other.ResponseType != 0) {
        ResponseType = other.ResponseType;
      }
      if (other.Attachment.Length != 0) {
        Attachment = other.Attachment;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ResponseType = (global::Com.Bdl.Proto.HeartbeatResponse.Types.ResponseType) input.ReadEnum();
            break;
          }
          case 18: {
            Attachment = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the HeartbeatResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum ResponseType {
        /// <summary>
        ///正常，程序接收到，什么都不用干。大部分情况是这个，先查库，没有下发对指令就回复这个。
        /// </summary>
        [pbr::OriginalName("NOMAL")] Nomal = 0,
        /// <summary>
        ///延期使用，用于增加使用时长，对9999对无效
        /// </summary>
        [pbr::OriginalName("ADDUSETIME")] Addusetime = 1,
        /// <summary>
        ///冻结指令
        /// </summary>
        [pbr::OriginalName("LOCK")] Lock = 2,
        /// <summary>
        ///解冻冻结
        /// </summary>
        [pbr::OriginalName("UNLOCK")] Unlock = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
